### PR TITLE
Fix missing manual cross-references to guide-build

### LINKED ISSUE #158: The manual has missing cross-references
The MPS manual has some missing cross-references.  References to the build instructions, such as at https://memory-pool-system.readthedocs.io/en/latest/topic/porting.html#update-the-documentation show as "guide-build" without a link.

A clean build of the manual at e179634de028b2db090ee6a2358391155102b74f on Ubuntu 22 generates these warnings:
```
/home/rb/git/mps/manual/source/code-index.rst:19: WARNING: Failed to create a cross reference. A title or caption not found: guide-build
/home/rb/git/mps/manual/source/glossary/c.rst:567: WARNING: Failed to create a cross reference. A title or caption not found: guide-build
/home/rb/git/mps/manual/source/guide/lang.rst:18: WARNING: Failed to create a cross reference. A title or caption not found: guide-build
/home/rb/git/mps/manual/source/guide/overview.rst:58: WARNING: Failed to create a cross reference. A title or caption not found: guide-build
/home/rb/git/mps/manual/source/guide/overview.rst:145: WARNING: Failed to create a cross reference. A title or caption not found: guide-build
/home/rb/git/mps/manual/source/release.rst:918: WARNING: Failed to create a cross reference. A title or caption not found: guide-build
/home/rb/git/mps/manual/source/release.rst:921: WARNING: Failed to create a cross reference. A title or caption not found: guide-build
/home/rb/git/mps/manual/source/topic/porting.rst:6: WARNING: Failed to create a cross reference. A title or caption not found: guide-build
/home/rb/git/mps/manual/source/topic/porting.rst:244: WARNING: Failed to create a cross reference. A title or caption not found: guide-build
/home/rb/git/mps/manual/source/topic/porting.rst:313: WARNING: Failed to create a cross reference. A title or caption not found: guide-build
/home/rb/git/mps/manual/source/topic/scanning.rst:559: WARNING: Unparseable C cross-reference: 'void *'
Invalid C declaration: Expected identifier in nested name, got keyword: void [error at 4]
  void *
  ----^
/home/rb/git/mps/manual/source/topic/telemetry.rst:75: WARNING: Failed to create a cross reference. A title or caption not found: guide-build
```

Some kind of anchor has gone missing from [build.txt](https://github.com/Ravenbrook/mps/blob/master/manual/build.txt).

### PR DESCRIPTION
**Pull request by rptb1**
Fixes the Sphinx markup so that references to "Building the MPS" from the manual link correctly.

Corrects the manual Makefile that prevented the above being detected.

Adds a note to prevent a similar mistake being introduced again.

Fixes #158 .

### CODE REVIEW

**Comment by rptb1** [comment]
Executing [proc.review.entry](https://github.com/Ravenbrook/mps/blob/4634a33f18dc6b30675235405ca43a3636f4942b/procedure/review.rst#51-review-entry)

1. Start time 06:06.
2. proc.review.entry.express: Change is small and low risk but nobody is available for express review. Plan to batch with other similar changes on 2023-02-23.
3. Entry passed.
4. Entry took 3 minutes.

**Comment by rptb1** [comment]
Executing [proc.review.plan](https://github.com/Ravenbrook/mps/blob/4634a33f18dc6b30675235405ca43a3636f4942b/procedure/review.rst#52-review-planning)

1. Start time 06:10.
2. proc.review.plan.time: Checking should take no longer than 10 minutes.
3. proc.review.plan.schedule: @thejayps @UNAA008 @rptb1 will review on 2023-02-12 11:00.
4. proc.review.plan.rule: [rule.generic](https://github.com/Ravenbrook/mps/blob/branch/2023-01-19/review-procedure/procedure/rule.generic.rst) [rule.style](https://github.com/Ravenbrook/mps/blob/branch/2023-01-19/review-procedure/procedure/rule.style.rst)
5. We'll assign roles at kickoff.
6. Planning took 6 mins.

**Comment by rptb1** [comment]
The definition in the manual here https://github.com/Ravenbrook/mps/blob/681e44334b3a93122ed91a8bf44a9820b681482d/manual/source/topic/pool.rst?plain=1#L175 is inconsistent with the one in the design here https://github.com/Ravenbrook/mps/blob/681e44334b3a93122ed91a8bf44a9820b681482d/design/object-debug.txt?plain=1#L350 producing a warning from Sphinx.

What's mysterious is *why*.  The definition in the design document was [removed](https://github.com/Ravenbrook/mps/pull/34/files#diff-ad8f557930c8c718ee1919da18e146370def7ef151d51a78b164aa9a8ea066a8) in #34 which was supposedly merged.

So why is it still there in master?

**Comment by rptb1** [comment]
> Something very odd has happened.

It looks like the definitions were reintroduced [during the *merge*](https://github.com/Ravenbrook/mps/pull/67#issuecomment-1396649218) of #67 , here https://github.com/Ravenbrook/mps/commit/081d79ee2299509615b67cdbe8f0bfdfbd93feab#diff-ad8f557930c8c718ee1919da18e146370def7ef151d51a78b164aa9a8ea066a8 .  The question now is how that happened, and how to prevent it.

**Comment by rptb1** [comment]
Executing [proc.review.kickoff](https://github.com/Ravenbrook/mps/blob/4634a33f18dc6b30675235405ca43a3636f4942b/procedure/review.rst#53-review-kickoff)

1. Start time 13:14.
2. @UNAA008 proc.review.role.check.{clarity,correctness,source}  @rptb1 proc.review.roll.check.{backwards,consistency,convention}
3. Logging will be at 13:45.
4. Kickoff took 6 minutes.

**Review by rptb1 — COMMENTED** [review]
Executing proc.review.check

1. Start time 13:28
2. Checked Sphinx documentation against extension again.
3. Clean build of manual seems good.
4. IM: There's nothing causing updates of "Old design". See also #128 .
5. Im: The design section of the manual just starts, without an intro or explanation.
6. Im: The manual doesn't index tags.
7. q: Are checkers looking at proc.review.check?
8. Found: 1 major, 2 minor, 1 question.
9. Checking took 17 mins.

**Review by UNAA008 — COMMENTED** [review]
I am reviewing the files for clarity and correctness and using #158 as a source document.
Q I noticed several instances of ??? in design/object-debug.txt - do these represent TODOs?
m Build.RST contains no header comments.

Comment that it takes longer to properly review the changed douments than is appropriate for this specific case.

**Comment by rptb1** [comment]
Executing [proc.review.log](https://github.com/Ravenbrook/mps/blob/4634a33f18dc6b30675235405ca43a3636f4942b/procedure/review.rst#55-review-logging)

1. Start time 13:50.
2. Re-writing log because GitHub threw it away (again).



> Q I noticed several instances of ??? in design/object-debug.txt - do these represent TODOs?

These are minor defects in design.mps.object-debug and need correcting.

> m Build.RST contains no header comments

That's true of all the manual sources and should be fixed.

**Comment by rptb1** [comment]
Executing [proc.review.edit](https://github.com/Ravenbrook/mps/blob/4634a33f18dc6b30675235405ca43a3636f4942b/procedure/review.rst#57-review-edit)

1. Start time 15:30.

> I am reviewing the files for clarity and correctness and using #158 as a source document. Q I noticed several instances of ??? in design/object-debug.txt - do these represent TODOs?

Fixed: Annotated with actual TODOs in 507ab8920 .

> m Build.RST contains no header comments.

Raise: https://github.com/Ravenbrook/mps/issues/172#issuecomment-1441986387

> Comment that it takes longer to properly review the changed douments than is appropriate for this specific case.

Answer: Noted.  But please clarify "appropriate" with reference to effort per review as a whole.

> IM: There's nothing causing updates of "Old design". See also #128 .

Raise: https://github.com/Ravenbrook/mps/issues/128#issuecomment-1442007159

2. Edit session suspended 15:50.

**Comment by rptb1** [comment]
Executing [proc.merge.pull-request](https://github.com/Ravenbrook/mps/blob/e179634de028b2db090ee6a2358391155102b74f/procedure/pull-request-merge.rst)

1. Start time 17:39.
2. An automated test case for this particular issue isn't really feasible *but* this branch does enable warnings as errors in Sphinx and so similar problems will be detected.
3. As I write, a few CI tests are still running, but they are on the MPS code, which this does not touch.
4.  I tested that the merged manual built cleanly, just for good measure: `make -C manual clean html`
5. Merging took 9 minutes.

**Pull request merged**
