### PR TITLE
Remove mps_telemetry_control, deprecated since release 1.111.0

### PR DESCRIPTION
**Pull request by gareth-rees**

### CODE REVIEW

**Review by UNAA008 — COMMENTED** [review]
I think manual/source/topic/security.rst should be modified as part of this change.

**Comment by gareth-rees** [comment]
> I think manual/source/topic/security.rst should be modified as part of this change.

Can you say what changes you would like?

**Comment by UNAA008** [comment]
> 
> 
> > I think manual/source/topic/security.rst should be modified as part of this change.
> 
> Can you say what changes you would like?

Apologies, I was in error.  My case-insensitive brain conflated "mps_telemetry_control" with "MPS_TELEMETRY_CONTROL".  I guess the security issue remains unchanged.

**Review by rptb1 — APPROVED** [review]
Looks good to me.

**Pull request merged**
